### ISSUE TITLE
API server at 5001 not working

### ISSUE THREAD

**Issue by tomurlh** [udacity/reactnd-contacts-complete#10]
I'm at nanodegree program of react and when I cloned the project, it started, but the API server is not working. The console shows `http://localhost:5001/contacts net::ERR_CONNECTION_REFUSED`.

I run the `npm install` and `npm start`, am I forgetting something?

**Comment by erikvp** [comment]
I used the following to run the server at localhost:5001:
`$ node server.js`
`Server listening on port 5001, Ctrl+C to stop`

For the React application running on localhost:3000:
`$ yarn start`
But it also works using:
`$ npm start`
